export const buildingImages = [
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-01.webp', alt: 'Kattegård ved Mathopen Kattepensjonat – romslig uteområde for kattene', width: 1536, height: 2048 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-02.webp', alt: 'Skjermet kattegård med klatremuligheter og skjulesteder', width: 1086, height: 1448 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-03.webp', alt: 'Kattegård sett innenfra – trygt og stimulerende uterom', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-04.webp', alt: 'Katter i fri lek i kattegården på Mathopen Kattepensjonat', width: 1086, height: 1448 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-05.webp', alt: 'Leke- og klatreområde i kattegården', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-06.webp', alt: 'Skjermet uteområde med naturlig lys i Bergen vest', width: 1023, height: 1537 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-07.webp', alt: 'Kattegård med god plass og naturlig belysning', width: 941, height: 1672 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-08.webp', alt: 'Rolig utegård med skjulesteder for katter som trenger ro', width: 1875, height: 839 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-kattegård-09.webp', alt: 'Oversiktsbilde over uteområdet på Mathopen Kattepensjonat', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innvending-01.webp', alt: 'Innvendig oversikt over Mathopen Kattepensjonat', width: 941, height: 1672 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innvendig-02.webp', alt: 'Fellesarealer inne på pensjonatet', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innvendig-03.webp', alt: 'Rent og luftig innvendig miljø på Mathopen Kattepensjonat', width: 941, height: 1672 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innvendig-04.webp', alt: 'Korridorer og rom innvendig på pensjonatet', width: 1672, height: 941 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innvendig-kattetårn.webp', alt: 'Kattetårn for klatring og stimulering på pensjonatet', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-standard-bur.webp', alt: 'Standard rom på Mathopen Kattepensjonat – plass til 1–2 katter', width: 1672, height: 941 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-suite-og-senior.webp', alt: 'Suite og senior & comfort rom side om side', width: 941, height: 1672 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innside-av-suite.webp', alt: 'Innside av suite-rommet – plass til opptil 3 katter fra samme husstand', width: 1080, height: 1920 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-utebur.webp', alt: 'Utebur tilknyttet Mathopen Kattepensjonat', width: 941, height: 1672 },
  { src: '/utforsk-pensjonatet/mathopen-kattepensjonat-innside-av-utebur-.webp', alt: 'Innside av utebur – kattene får tilgang til frisk luft', width: 941, height: 1672 },
]
